import type { ReactNode } from 'react';
import { Printer } from 'lucide-react';
import { Button } from '../../shared/components/ui/button';
import { Badge } from '../../shared/components/ui/badge';

/** The on-screen title + action row for a report — hidden on print; the printed document has its own masthead (see ReportDocument). */
export function ReportHeader({ title, description, isDemo, actions }: { title: string; description: string; isDemo?: boolean; actions?: ReactNode }) {
  return (
    <div className="flex flex-wrap items-center justify-between gap-4 print:hidden">
      <div className="flex items-center gap-2">
        <div>
          <h1 className="text-xl font-semibold tracking-tight">{title}</h1>
          <p className="text-sm text-muted-foreground">{description}</p>
        </div>
        {isDemo && <Badge variant="warning">Sample data</Badge>}
      </div>
      <div className="flex flex-wrap items-center gap-2">
        {actions}
        <Button variant="primary" size="sm" onClick={() => window.print()}>
          <Printer className="h-4 w-4" />
          Print / Save as PDF
        </Button>
      </div>
    </div>
  );
}

/** Two-column label/count table — the print-friendly, exact-figures counterpart to BarChart, used across report sections. */
export function ReportDataTable({ rows, labelHeader = 'Category', valueHeader = 'Cases' }: { rows: Array<{ label: string; value: number }>; labelHeader?: string; valueHeader?: string }) {
  if (rows.length === 0) return <p className="mt-1 text-sm text-muted-foreground">Not enough data yet.</p>;
  return (
    <table className="mt-2 w-full text-sm">
      <thead>
        <tr className="border-b border-border text-left text-xs uppercase tracking-wide text-muted-foreground">
          <th className="py-1.5 font-medium">{labelHeader}</th>
          <th className="py-1.5 text-right font-medium">{valueHeader}</th>
        </tr>
      </thead>
      <tbody>
        {[...rows]
          .sort((a, b) => b.value - a.value)
          .map((row) => (
            <tr key={row.label} className="border-b border-border last:border-0">
              <td className="py-1.5 text-foreground">{row.label}</td>
              <td className="py-1.5 text-right font-medium text-foreground">{row.value}</td>
            </tr>
          ))}
      </tbody>
    </table>
  );
}

/** The printable document shell itself — masthead stays visible on paper, unlike ReportHeader's on-screen controls. */
export function ReportDocument({ title, generatedNote, children }: { title: string; generatedNote: string; children: ReactNode }) {
  return (
    <div className="rounded-lg border border-border bg-card p-8 print:rounded-none print:border-0 print:p-0">
      <div className="mb-6 border-b border-border pb-4">
        <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">WARD — Workplace for AI-assisted Research &amp; Detection</p>
        <h2 className="mt-1 text-lg font-semibold text-foreground">{title}</h2>
        <p className="text-xs text-muted-foreground">{generatedNote}</p>
      </div>
      <div className="space-y-6">{children}</div>
      <div className="mt-8 border-t border-border pt-3 text-[11px] text-muted-foreground">
        Generated by WARD for official investigative use. Sections marked "Sample data" reflect demonstration data, not real case activity.
      </div>
    </div>
  );
}
